version: "3.9"

services:
  app:
    build:
      context: .
      target: app
    image: fleetlm:latest
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:-xuQnOFm6sH5Qdd7x4WJv5smuG2Xf2nG0BL8rJ4yX6HnKGeTjo6n8r5hQKsxNkZWz}
      DATABASE_URL: ecto://postgres:postgres@db/fleetlm_dev
      PHX_HOST: ${PHX_HOST:-localhost}
      PORT: 4000
      MIGRATE_ON_BOOT: ${MIGRATE_ON_BOOT:-true}
      # DNS clustering is disabled locally; set DNS_CLUSTER_QUERY in deployments
      DNS_CLUSTER_QUERY: ${DNS_CLUSTER_QUERY:-}
      DNS_CLUSTER_NODE_BASENAME: ${DNS_CLUSTER_NODE_BASENAME:-fleetlm}
      DNS_POLL_INTERVAL_MS: ${DNS_POLL_INTERVAL_MS:-5000}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fleetlm_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data:
