name: Deploy Docs to Cloudflare Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'docs-site/**'
      - '.github/workflows/deploy-docs.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: docs-site/package-lock.json

      - name: Install dependencies
        working-directory: docs-site
        run: npm install

      - name: Build site
        working-directory: docs-site
        env:
          DOCUSAURUS_SITE_URL: https://docs.fleetlm.com
          DOCUSAURUS_BASE_URL: /
        run: npm run build

      - name: Deploy to Cloudflare Pages
        working-directory: docs-site
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npx wrangler pages deploy
