name: Test Suite

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fastpaca_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      MIX_ENV: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.18.4'
        otp-version: '28.0'

    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Setup test database
      run: mix ecto.setup
      env:
        MIX_ENV: test

    - name: Run tests
      run: mix test --trace

#    - name: Run tests with coverage
#      run: mix test --cover
#      if: success() || failure()

#    - name: Upload coverage reports
#      uses: codecov/codecov-action@v3
#      if: success() || failure()
#      with:
#        file: ./cover/excoveralls.json
#        flags: unittests
#        name: codecov-umbrella
#        fail_ci_if_error: false
